### ISSUE TITLE
Altura 2x

### ISSUE THREAD

**Issue by Israel-Carneiro** [lilian-rangel/Projeto-Calculadora-IMC#1]
Olá Lilian, estava conferindo seu projeto (e checando meu IMC tbm ✔), mas logo percebi um pequeno erro de atenção.
A calculadora pede a "Altura" no lugar do peso:

![2022-11-08](https://user-images.githubusercontent.com/113190387/200646972-4235262b-2cac-4bcb-a149-c871a00e24ac.png)

**Comment by lilian-rangel** [comment]
Oi Israel.
Muito obrigada pelo feedback!

Erro de digitação arrumado :)
